version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Expose the frontend on localhost:3000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Expose the backend on localhost:5000
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://database:27017/mydatabase  # Connect to MongoDB in the same network
    env_file:
      - ./.env

  database:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB on localhost:27017
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
