apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abdulsubhan303/mlops_assignment_2-frontend:latest  
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Change to LoadBalancer if preferred
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Internal service port
      targetPort: 3000  # Container port
      nodePort: 30001  # Optional: specify node port
